---
name: On Merge

on:
    push:
        branches: [main]

jobs:
    test:
        uses: ./.github/workflows/job-test.yml
        permissions:
            contents: read
            id-token: write

    e2e:
        uses: ./.github/workflows/job-e2e.yml
        permissions:
            contents: read
        secrets: inherit

    docker:
        needs: test
        uses: ./.github/workflows/job-docker.yml
        permissions:
            contents: read
            packages: write
